### ISSUE TITLE
Update images for model bamf_nnunet_ct_kidney

### ISSUE THREAD

**Issue by jithenece** [MHubAI/models#91]
The sample screenshots for the below test case attached as zip file. Please update this under [bamf_nnunet_ct_kidney](https://mhub.ai/models/bamf_nnunet_ct_kidney) page
[Archive.zip](https://github.com/user-attachments/files/16127404/Archive.zip)

 /test

```yaml
sample:
  idc_version: "Data Release 3.0 May 29, 2020"
  data:
  - SeriesInstanceUID: 1.3.6.1.4.1.14519.5.2.1.9203.4004.385483163880959624431394063795
    aws_url: s3://idc-open-data/43b672b6-dd41-4a00-a1ad-dd5a8cf407df/*
    path: dicom

reference:
  url: https://drive.google.com/file/d/1bs374v9Kbw738W8y3_LNIsFA37_FAtP6/view?usp=sharing
```
